
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: milda
      POSTGRES_PASSWORD: 1za200
      POSTGRES_DB: eshop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: